### ISSUE TITLE
Speller is not built

### ISSUE THREAD

**Issue by albbas** [giellalt/lang-sme#1] opened 2020-05-19 10:13 UTC
This config:
`./configure --with-hfst --without-xfst --enable-alignment --enable-reversed-intersect --without-forrest --enable-spellers`

Leads to this error message:

make[3]: Entering directory '/home/boerre/gut/giellalt/lang-sme/tools/spellcheckers'
  HXFST    generator-speller-gt-norm.tmp.hfst
  CP       generator-speller-gt-norm.hfst
  HINVERT  analyser-speller-gt-norm.hfst
  HXFST    generator-fstspeller-gt-norm.tmp.hfst
  HXFST    generator-fstspeller-gt-norm.hfst
  HINVERT  analyser-fstspeller-gt-norm.hfst
  HFST2FST generator-desktopspeller-gt-norm-base.hfst
  HREWGHT  unitweighted.hfst
  HCOMPOSE generator-desktopspeller-gt-norm-freq_weighted.hfst
  HXFST    generator-desktopspeller-gt-norm-unit_weighted.hfst
  HREWGHT  generator-desktopspeller-gt-norm-tag_weighted.hfst
  HXFST    generator-desktopspeller-gt-norm.tmp.hfst
  HXFST    generator-desktopspeller-gt-norm.hfst
  HINVERT  analyser-desktopspeller-gt-norm.hfst
  HRGX2FST anystar.hfst
  GEN      easteregg.default.txt
Makefile:2298: recipe for target 'easteregg.default.txt' failed
make[3]: *** [easteregg.default.txt] Error 1
rm generator-desktopspeller-gt-norm-unit_weighted.hfst generator-desktopspeller-gt-norm-freq_weighted.hfst easteregg.default.txt
make[3]: Leaving directory '/home/boerre/gut/giellalt/lang-sme/tools/spellcheckers'
Makefile:1625: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/boerre/gut/giellalt/lang-sme/tools/spellcheckers'
Makefile:419: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/boerre/gut/giellalt/lang-sme/tools'
Makefile:520: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by aarppe** [comment] 2020-05-20 02:29
When I'd be compiling spellers for crk, I have not used two of the options above, i.e. using only:

`./configure --with-hfst --without-xfst --without-forrest --enable-spellers`

... but maybe someone/Sjur knows if those two options (`--enable-alignment` and `--enable-reversed-intersect`) are needed for creating a speller that can be incorporated in the repo? Otherwise they seem unnecessary, but only in my experience.

**Comment by snomos** [comment] 2020-05-20 05:57
`--enable-alignment` and `--enable-reversed-intersect` are not needed for speller creation, these are general fst optimisation flags (and should probably default to enabled in any case).

**Comment by snomos** [comment] 2022-11-04 11:05
Using the same configuration I am not able to reproduce. I thus close this one.

**Closed by snomos** 2022-11-04 11:05 UTC
